nomenclature:
  name: noticeboard
  verboseName: Noticeboard
baseUrls:
  http: noticeboard/
  ws: noticeboard/
isApi: true
acceptables:
  roles:
  - name: Student
    activeStatuses:
    - IS_ACTIVE
    - HAS_BEEN_ACTIVE
  - name: Faculty    
    activeStatuses:
    - IS_ACTIVE
    - HAS_BEEN_ACTIVE
categories:
  - name: Department
    slug: department
  - name: Authorities
    slug: authorities
