nomenclature:
  name: noticeboard
  verboseName: Noticeboard
baseUrls:
  http: noticeboard/
  ws: noticeboard/
  static: noticeboard/
isApi: true
acceptables:
  roles:
    - name: Student
      activeStatuses:
        - IS_ACTIVE
        - HAS_BEEN_ACTIVE
    - name: FacultyMember
      activeStatuses:
        - IS_ACTIVE
        - HAS_BEEN_ACTIVE
categorisation:
  - name: Authorities
    slug: authorities
  - name: Departments
    slug: departments
  - name: Centres
    slug: centres
  - name: Bhawans
    slug: bhawans
