nomenclature:
  name: noticeboard
  verboseName: Noticeboard
description: A digital e-noticeboard
baseUrls:
  http: noticeboard/
  ws: noticeboard/
  static: noticeboard/
isApi: true
acceptables:
  ipAddressRings:
    - internet
    - intranet
    - maintainers
    - specifics
    - administrator
    - self
  roles:
    - name: Student
      activeStatuses:
        - IS_ACTIVE
        - HAS_BEEN_ACTIVE
    - name: FacultyMember
      activeStatuses:
        - IS_ACTIVE
        - HAS_BEEN_ACTIVE
    - name: Guest
      activeStatuses:
        - IS_ACTIVE
        - HAS_BEEN_ACTIVE
categorisation:
  - name: Authorities
    slug: authorities
  - name: Departments
    slug: departments
  - name: Centres
    slug: centres
  - name: Bhawans
    slug: bhawans
