# Generated by Django 2.0.4 on 2018-08-26 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.KERNEL_PERSON_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('removed', models.DateTimeField(blank=True, default=None, editable=False, null=True)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
                ('entity_object_id', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=63)),
                ('entity_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banner', to='contenttypes.ContentType')),
            ],
        ),
        migrations.CreateModel(
            name='ExpiredNotice',
            fields=[
                ('removed', models.DateTimeField(blank=True, default=None, editable=False, null=True)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True)),
                ('expiry_date', models.DateTimeField()),
                ('send_email', models.BooleanField(default=False)),
                ('is_draft', models.BooleanField(default=False)),
                ('is_edited', models.BooleanField(default=False)),
                ('notice_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noticeboard.Banner')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('removed', models.DateTimeField(blank=True, default=None, editable=False, null=True)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=31)),
            ],
            options={
                'verbose_name_plural': 'main_categories',
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('removed', models.DateTimeField(blank=True, default=None, editable=False, null=True)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True)),
                ('expiry_date', models.DateTimeField()),
                ('send_email', models.BooleanField(default=False)),
                ('is_draft', models.BooleanField(default=False)),
                ('is_edited', models.BooleanField(default=False)),
                ('banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noticeboard.Banner')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('removed', models.DateTimeField(blank=True, default=None, editable=False, null=True)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
                ('persona_object_id', models.PositiveIntegerField()),
                ('banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noticeboard.Banner')),
                ('persona_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persona', to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name_plural': 'permissions',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('removed', models.DateTimeField(blank=True, default=None, editable=False, null=True)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
                ('is_subscribed_via_email', models.BooleanField(default=False)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notice_user', to=settings.KERNEL_PERSON_MODEL)),
                ('read_notices', models.ManyToManyField(blank=True, related_name='read_notice_set', to='noticeboard.Notice')),
                ('starred_notices', models.ManyToManyField(blank=True, related_name='starred_notice_set', to='noticeboard.Notice')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='banner',
            name='main_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noticeboard.MainCategory'),
        ),
        migrations.AlterUniqueTogether(
            name='banner',
            unique_together={('main_category', 'entity_content_type', 'entity_object_id')},
        ),
    ]
