# Generated by Django 3.0.3 on 2020-10-10 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticeboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expirednotice',
            name='pdf_path',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='notice',
            name='pdf_path',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
