# Generated by Django 4.1.5 on 2024-03-14 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticeboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expirednotice',
            name='notice_created_on',
            field=models.DateTimeField(null=True),
        ),
    ]
