# Generated by Django 2.2.3 on 2019-10-05 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticeboard', '0002_auto_20190904_0629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expirednotice',
            name='expiry_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='notice',
            name='expiry_date',
            field=models.DateField(),
        ),
    ]
