# Generated by Django 2.2.3 on 2019-10-14 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticeboard', '0004_auto_20191011_0251'),
    ]

    operations = [
        migrations.AddField(
            model_name='expirednotice',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notice',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
